### ISSUE TITLE
Ocarina Shuffle buttons working, songs not being recognised

### ISSUE THREAD

**Issue by ThatsGottaBeKane** [ThatsGottaBeKane/OoTMMR_tracker_pack#12]
should be a matter of just finding out where the original songs are and verifying the names used are correct, if not, more digging on this will be required

**Comment by Tsarchasm5** [comment]
need to wait until new version is released to see how my stuff fairs with the new logic, then go from there. should already be fixed

**Comment by Tsarchasm5** [comment]
new version of logic has switched a few things around, need to alter a few things code name wise and its good to go
