### ISSUE TITLE
broadcast view not working

### ISSUE THREAD

**Issue by ThatsGottaBeKane** [ThatsGottaBeKane/OoTMMR_tracker_pack#15]
(intentionally for now), until all new items have been successfully imported into their final place onto the main grid, then broadcast view can be done in one swoop, saving time

**Comment by Tsarchasm5** [comment]
mostly fixed now, just needs final touches

**Comment by Tsarchasm5** [comment]
needs testing from someone who uses it, as i don't. the logic and scriptings look fine so it SHOULD work but i cant really know until someone with more expertise in using broadcast view tests it
