### ISSUE TITLE
OOT Overworld Logic Child vs Adult

### ISSUE THREAD

**Issue by gamefunatic** [ThatsGottaBeKane/OoTMMR_tracker_pack#21]
Currently the "starting age" setting does nothing because there is no logic for requiring master sword for time travel. Child checks are always available while adult checks are not.

**Comment by Tsarchasm5** [comment]
thats because the master sword can be shuffled and also be attained by child link now so it logically cant be used this way any more. im working on a work around, but im on a short hiatus at the moment as ive got a few real life things happening at the moment that are taking up my priorities

**Comment by Tsarchasm5** [comment]
fixed and working as normal
